config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  resources :replies
  mount Notifications::Engine => "/notifications"
 resources :waitlists
 resources :line_items
 resources :carts
 resources :categories

 post 'line_items', to: 'line_items#show'
 get 'checkout', to: 'checkouts#show'

 get 'videos/index2'

 get 'purchases/orders'
 get 'purchases/previous_purchases'
 post 'purchases/show'

 get 'rentals_list/show'
 delete 'rentals_list/destroy', to: 'rentals_list#destroy'

 resources :charges
 resources :purchases, only: [:show]

 post 'videos/rent_form' 

 post 'videos/clear_cart' 
 get 'videos/cart' 

 get 'cart_list/show'

 post 'videos/add_to_cart/:id', to: 'videos#add_to_cart', as: 'add_to_cart' 
 delete 'videos/remove_from_cart/:id', to: 'videos#remove_from_cart', as: 'remove_from_cart' 

 devise_scope :user do
   get '/admin/sign_out' => 'devise/sessions#destroy'
 end


 devise_scope :customer do
   get '/home/sign_out' => 'devise/sessions#destroy'
 end

  resources :actors
  resources :videos do
   resources :reviews
   collection do
    get :autocomplete
   end
  end
  
  get 'users/edit_profile'
  devise_for :customers, path: 'home'
  devise_for :users, path: 'admin', :skip => [:registrations]

  scope '/admin' do 
    resources :genres
    resources :roles
    resources :users
  end

  scope '/home' do 
    resources :customers
  end

  scope '/customer' do
    get 'rentals_list/show'
    resources :copies
    resources :rent_items
    resources :cart_items
    resources :rentals_list, only: [:show]
  end   

  root :to => "videos#index" 

  post 'copies/new', to: 'copies#new'
  get '/users/clear', to: 'users#clear', as: 'clear'


  mount Sidekiq::Web => '/sidekiq'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/video.rb
class Video < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  belongs_to :user
  has_and_belongs_to_many :genres
  has_rich_text :description 
  has_one_attached :thumbnail
  has_many :copies, dependent: :destroy
  has_many :rent_items
  belongs_to :customer, optional: true
  belongs_to :category, optional: true
  has_many :reviews
  
  validates :rent_price, numericality: { only_decimal: true }, presence: true, allow_blank: false

  has_many :actors_videos
  has_many :actors, through: :actors_videos
  has_many :line_items
  has_many :order_items
  before_save :set_dvd
  before_save :set_vhs
  before_save :set_bluray
  before_save :set_stock
  #before_save :set_date

  
  accepts_nested_attributes_for :genres, reject_if: :all_blank


    def self.search(search)
        if search 
            where(["name LIKE ?","%#{search}%"])
        else
            all
        end
    end 
   
    def self.search_by(search_term)
      where("LOWER(name) LIKE :search_term", search_term: "%#{search_term.downcase}%")
    end

  private


  def not_referenced_by_any_line_item
     unless line_items.empty?
       errors.add(:base, "Line items present")
       throw :abort
     end
  end

  def set_date
    self[:rented_at] = self[:created_at]
  end

  def set_dvd
   if self[:dvd_copies] == nil
    self[:dvd_copies] = 0
   end
  end

  def set_vhs
   if self[:vhs_copies] == nil
    self[:vhs_copies] = 0
   end
  end

  def set_bluray
   if self[:bluray_copies] == nil
    self[:bluray_copies] = 0
   end
  end

  def set_stock
   if self[:stock] == nil
    self[:stock] = 0
   end
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  load_and_authorize_resource
  before_action :initialize_search, only: :index
  before_action :initialize_session
  before_action :increment_visit_count, only: :index
 # before_action :load_cart
  #before_action :load_customer
  
  # GET /videos
  def index
    @rent_item = current_rent.rent_items.new
   # @cart_item = current_cart.cart_items.new
    @videos = Video.paginate(page: params[:page], per_page: 4)
    @recent_videos = Video.all.order('created_at DESC').limit(4).offset(1)
    @videos = Video.search(params[:search]).paginate(page: params[:page], per_page: 4) 
    @genres = Genre.all
    handle_filters
    #@cart = Cart.find(session[:cart_id])
  end


 # def add_to_cart
   # if customer_signed_in?
   #   id = params[:id].to_i
   #   session[:cart] << id unless session[:cart].include?(id)
   #   redirect_to root_path
   #  else
   #   redirect_to new_customer_session_path
   # end

 # end


  #def remove_from_cart
   # id = params[:id].to_i
   # session[:cart].delete(id)
  #  redirect_to videos_cart_path
  #end

  # GET /videos/1
  def show

    if customer_signed_in?
     #@rent_item = current_customer.rent_items.new 
    end
    @customer = current_customer if customer_signed_in?
    @categories = Category.all.map{ |c| [c.name, c.id] } 
    @cart_item = current_cart.cart_items.new
    if @video.genres.empty?
      @associated_genres = 'None'
    else
      @associated_genres = @video.genres.map(&:name).join("/ ")
    end
    if customer_signed_in?
     @cart_items = current_customer.cart_items.to_a
    end

   @waitlists = Waitlist.all
   
   @waitlist = Waitlist.new

 
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end


  # POST /videos
  def create
    @video.user_id = current_user.id
    if @video.save
      user = @video.user
      redirect_to @video, notice: 'Video was successfully created.'
      CustomerMailer.new_video(user, @video).deliver_now
      sleep 2
    else
      render :new
    end
  end

  # PATCH/PUT /videos/1
  def update
    if @video.update(video_params)
      redirect_to @video, notice: 'Video was successfully updated.'
      if @video.stock > 0
        @waitlists = Waitlist.all
        @waitlists.each do |waitlist|
          if waitlist.video_id == @video.id
            email = waitlist.email
            video = Video.find(waitlist.video_id)
            WaitlistsMailer.stock_available(email, video).deliver_now
            waitlist.destroy
          end
        end
      end
    else
      render :edit
    end
  end

  # DELETE /videos/1
  def destroy

    @video = Video.find(params[:id])
    @video.delete
    redirect_to videos_url, notice: 'Video was successfully destroyed.'
  end

  def autocomplete
    render json: Video.search(params[:query], {
      fields: ["name^5"],
      match: :word_start,
      limit: 10,
      load: false,
      misspellings: {below: 5} 
    }).map(&:name)
  end


  def rent_form
    @rent_item = current_rent.rent_items.new

    @video = Video.find(params[:video_id])

    @categories = Category.all.map{ |c| [c.name, c.id] } 
   # @video.category_id = params[:category_id]
    @category_id = params[:category_id]
    @category = Category.find(params[:category_id])

  end

  def index2
    @videos = Video.order(params[:sort])
  end

  def clear_cart
    session[:cart] = [] 
    redirect_to videos_cart_path
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:name, :description, :thumbnail, :rent_price, :user_id, :stock, :dvd_copies, :vhs_copies, :bluray_copies, :genre_ids => [], :actor_ids=>[])
    end

  def initialize_search
    params[:search]
    params[:filter]
    params[:filter_option] = nil if params[:filter_option] == ""
    params[:filter_option]
  end

  def handle_search_name
    if params[:search]
      @videos = Video.where("name like ?", "%#{params[:search].titleize}%")
      
      @genres = @genres.where(id: @videos.pluck(:genre))
    end
  end

  def handle_filters
    if params[:filter_option] && params[:filter] == "genre"
      @genres = @genres.where(id: params[:filter_option])
    end
  end

  def initialize_session
    session[:visit_count] ||= 0 unless current_customer.nil?
    session[:customer_id] ||= current_customer.id if customer_signed_in?
    session[:cart] ||= [] 
    session[:quantity] = 1
  end

  def load_cart
   @cart = Video.find(session[:cart]) 
  end
 

  def load_customer
    @customer = Customer.find(session[:customer_id]) if customer_signed_in?
  end

  def increment_visit_count
    session[:visit_count] += 1 unless current_customer.nil?
    @visit_count = session[:visit_count]
  end

end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_with(model: video) do |f| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.rich_text_area :description %>
  </div>

  <div class="field">
    <%= f.label :thumbnail %>
    <%= f.file_field :thumbnail %>
  </div>


  <div class="field">
    <%= f.collection_check_boxes(:genre_ids, Genre.all, :id, :name) %>
  </div>

  <div class="form-group">
    <%= f.label :actors %>
    <%= f.collection_select :actor_ids, Actor.order(:name), :id, :name, {}, { class: 'form-control select2', multiple: true } %>
  </div>

  <div class="field">
    <%= f.label :rent_price %>
    <%= f.number_field :rent_price, step: :any, :value => video.rent_price, :min => 1.0 %>
  </div>
<br/>
<h5>Avaliable copies </h5>
<div class="field">
<table class="table table-borderless">
  <tr class="table-light">
    <td><strong>DVD copies: </strong><%= f.number_field :dvd_copies, step: :any, :value => video.dvd_copies, :min => 0 %></td>
    <td><strong>VHS copies: </strong><%= f.number_field :vhs_copies, step: :any, :value => video.vhs_copies, :min => 0 %></td>
    <td><strong>BLU-RAY copies: </strong><%= f.number_field :bluray_copies, step: :any, :value => video.bluray_copies, :min => 0 %></td>
  </tr>
</table>
</div>
<h5>Stock available </h5>
<div class="field">
  <%= f.number_field :stock, step: :any, :value => video.stock, :min => 0 %>
</div>
<br/>
  <div class="actions">
    <%= f.submit class: "btn btn-warning " %>
  </div>
<% end %>

app/views/videos/_video.html.erb
<% if current_user && current_user.admin? %>
	<li class="category-link">
		<div>
		  <span class="badge bg-light"><%= link_to video.name, video %></span><br/> 
		</div>
<% end %>

app/views/videos/cart.html.erb
<h1>CART</h1>


<% if current_customer %>
    <summary>Shopping Cart Items</summary>
    <% if @cart.empty?%>
      <p>No items in cart.</p>
    <% else %>
     <ul>
      <% @cart.each do |video| %>
       <h2><%= video.name %></h2>
       <%= image_tag(video.thumbnail, size: '180x155', class: "img-responsive") if video.thumbnail.present? %></li><br/>
<div class="form-group col-md-2"><br/>
Qty: <%= number_field_tag 'quantity', nil, min: 1, max: 10, value: 1, class: "form-control" %>
</div><br/><br/>
<h4>Price: <%= video.rent_price*2 %></h4><br/>
<%= link_to 'Remove from cart', remove_from_cart_path(video), method: :delete %>
      <% end %>
     </ul>
   <%= button_to 'Clear cart', videos_clear_cart_path %>
    <% end %>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>
<br/>
<%= link_to 'Back', videos_path, class: "btn btn-outline-secondary btn-sm" %>  || 
<%= link_to 'Show', @video, class: "btn btn-outline-secondary btn-sm" %>

app/views/videos/index.html.erb
<h1>Videos</h1>

<%= form_with(url: '/videos', method: 'get', local: true) do %>
  <%= search_field_tag 'search', nil, id: 'videos_search', autocomplete: :off, placeholder: "Search Videos..", value: params[:search]  %>
  <%= submit_tag("Search", class: "btn btn-outline-secondary") %>
  <%= link_to "Clear", root_path, class: "btn btn-outline-secondary" %>
<% end %>

<form action="/videos" method="GET">
  <label for="filter">Filter Options</label>
  <select id="filter" name="filter" onchange="this.form.submit()">
    <option value="">Pick a Filter Option</option>
    <option value="genre" <%= "selected" if params[:filter] == "genre" %>>Filter by Genre</option>
  </select>
  <% if params[:filter] == "genre" %>
    <select name="filter_option" onchange="this.form.submit()">
      <option value="">Pick a Genre</option>
      <% @genres.each do |genre| %>
        <option value="<%= genre.id %>"><%= genre.name %></option>
      <% end %>
    </select>
  <% end %>
</form>

<% if params[:search].present? %>
     <br />
	<p>
	  Your search for <strong>'<%= params[:search] %>'</strong> returned <%= pluralize(@videos.size, 'result') %>. 
	</p>
<% end %>
<br/>
      <div class="card-deck ">
       <div class="row row-cols-1 row-cols-md-3">
       <% if !@videos.empty? %>
        <% @videos.each do |video| %>
           <div class="col mb-4">
            <div class = "recipe">
              <div class="image-wrapper">
                <%= link_to video do %>
                  <%= image_tag(video.thumbnail, size: '310x285', class: "img-responsive rounded") if video.thumbnail.present? %>
                <% end %>
              </div>
	      <div class="card-body">
                 <h3 class="card-title"><%= link_to video.name, video %></h3>
                 <p class="card-text"><%= link_to video.description, video %></p>
             </div>

	      <div class="card-footer">
                <% 5.times do %>
                   <i class="bi bi-star-fill"></i>
               <% end %>
              </div>
              <br/>
            <div>
          </div>
     </div>
 </div>
<% end %>
<% else %>
<div>
  <h4> No matching results found! </h4><br/>
</div>
<% end %>
<div>
<%= will_paginate @videos, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div><br />
 <div class="card-deck ">
<h2>New Arrivals</h2>
       <div class="row row-cols-1 row-cols-md-3">
        <% @recent_videos.each do |video| %>
          <% unless @cart.cart_items.include?(video) %>
           <div class="col mb-4">
            <div class = "recipe">
              <div class="image-wrapper">
                <%= link_to video do %>
                  <%= image_tag(video.thumbnail, size: '310x285', class: "img-responsive rounded") if video.thumbnail.present? %>
                <% end %>
              </div>
	      <div class="card-body">
                 <h3 class="card-title"><%= link_to video.name, video %></h3>
                 <p class="card-text"><%= link_to video.description, video %></p>
             </div>

	      <div class="card-footer">
               <% if @cart.cart_items.include?(video) %>
                 <small><p>Video is in your cart!</p></small>
                 <small class="text-muted"><strong><%= link_to 'Remove from cart <--', line_item, method: :delete, data: { confirm: "Are you sure? " } %></strong></small>
               <% else %>
                <small class="text-muted"><strong><%= button_to 'Add to cart -->', line_items_path(video_id: video.id) %></strong></small>
               <% end %>
              </div>
              <br/>
            <div>
          </div>
     </div>
 </div>
<% end %>
<% end %>

<br>
<div class="shadow-lg p-3 mb-5 bg-white rounded">
<% if can? :create, Video %>
  <%= link_to 'New Video', new_video_path, class: "btn btn-outline-secondary" %>
<% end %>
<br>
</div>

app/views/videos/index2.html.erb
<h1>Videos</h1>

<%= form_for "", url: videos_index2_path, role: "search", method: :get do %>
  <%= text_field_tag :search, @search_term, placeholder: "Search..." %>
  <%= submit_tag "Search", class: "btn btn-outline-secondary" %>
  <%= link_to "Clear", videos_index2_path, class: "btn btn-outline-secondary" %>
<% end %>

<br/>
<table>
  <thead>
    <tr>
      <th rowspan="2"><%= link_to "Id", :sort => "id" %></th>
      <th rowspan="2"><%= link_to "Name", :sort => "name" %></th>
      <th rowspan="2"><%= link_to "Item Price", :sort => "rent_price" %></th>
      <th rowspan="2"><%= link_to "Available stock", :sort => "stock" %></th>
      <th colspan="3">Rental Copies available</th>
    </tr>
   <tr>
      <th><%= link_to "DVD", :sort => "dvd_copies" %> ($<%= Category.find(1).price %>/day)</th>
      <th><%= link_to "VHS", :sort => "vhs_copies" %> ($<%= Category.find(2).price %>/day)</th>
      <th><%= link_to "BLU-RAY", :sort => "bluray_copies" %> ($<%= Category.find(3).price %>/day)</th>

    </tr>
  </thead>

  <tbody>
    <% if @videos.empty? %>
      <tr>
         <td colspan="7" class="text-center">Sorry, no videos are available. :)</td>
      </tr>
    <% else %>
    <% @videos.each do |video| %>
        <tr>
          <td><%= video.id %></td>
          <td><%= link_to video.name, video %></td>
          <td>$<%= video.rent_price*2 %></td>
          <% if video.stock == 0 %>
            <td><small><strong>Out of stock</strong></small></td>
          <% else %>
            <td><%= video.stock %></td>
          <% end %>
          <td><%= link_to video.dvd_copies, edit_video_path(video) %></td>
          <td><%= link_to video.vhs_copies, edit_video_path(video) %></td>
          <td><%= link_to video.bluray_copies, edit_video_path(video) %></td>
        </tr>
    <% end %>
   <% end %>
  </tbody>
</table>
<%# link_to 'Export ~>', users_path(format: :xlsx) %>
<nav>
<br/>
<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>
<br/>
<%= link_to 'Back', videos_path, class: "btn btn-outline-secondary btn-sm" %>

app/views/videos/rent_form.html.erb
<p>
  <strong>Rent price:</strong>
  $<%= @category.price %>/day
</p>

	<%= form_for @rent_item, remote: true do |f| %>
	  <%= f.hidden_field :customer_id, :value => current_customer.id unless !customer_signed_in? %>
	  <%= f.hidden_field :video_id, :value => @video.id %>
	  <%= f.hidden_field :category_id, :value => @category_id.to_i  %>
<br/><br/>
        <% if @category_id.to_i == 1 %>
	  No of copies: <%= f.number_field :copies, :value => 1, :min => 1, :max => @video.dvd_copies, required: true %><small> Only <%= pluralize(@video.dvd_copies, 'copy')%> available!</small><br/><br/>
        <% elsif @category_id.to_i == 2 %>
	  No of copies: <%= f.number_field :copies, :value => 1, :min => 1, :max => @video.vhs_copies, required: true %><small> Only <%= pluralize(@video.vhs_copies, 'copy') %> available!</small><br/><br/>
        <% elsif @category_id.to_i == 3 %>
	  No of copies: <%= f.number_field :copies, :value => 1, :min => 1, :max => @video.bluray_copies, required: true %><small> Only <%= pluralize(@video.bluray_copies, 'copy') %> available!</small><br/><br/>
        <% end %>

  Expected return: <%= f.text_field :return_date, required: true, :value => Date.today+1,
    data: {
      controller: "flatpickr",
      flatpickr_date_format: "Y-m-d",
      flatpickr_min_date: Date.today+1
    }, required: true %><small> Rent at least for a day!</small>


	  <br/><br/>
	  <%= f.submit "Add to list " %>

	<% end %>

app/views/videos/show.html.erb
<%= image_tag(@video.thumbnail, size: '310x285') if @video.thumbnail.present? %>
<p>
  <strong>Name:</strong>
  <%= @video.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<p>
  <strong>Video Genres:</strong>
  <%= @associated_genres %>
</p>

<p>
  <strong>Actors:</strong>
  <%= render @video.actors.order('name ASC') %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @video.user.first_name %>
</p>

<p>
  <strong>Video price:</strong>
  $<%= @video.rent_price*2.round(2) %>
</p>

<% if customer_signed_in? %>
	<strong>Rent copies of: </strong>
	<table>
	 <tr>
	   <% if @video.dvd_copies == 0 %>
	       <h5><strong><span class="badge bg-secondary">Out of DVD copies!</span></strong></h5> 
	   <% else %>
	       <%= button_to 'DVD', videos_rent_form_url(:video_id => @video.id, :category_id => @category_id = 1 ), method: :post, class: "btn btn-success btn-sm active" %> 
	   <% end %>

	   <% if @video.vhs_copies == 0 %>
	       <h5><strong><span class="badge bg-secondary">Out of VHS copies!</span></strong></h5> 
	   <% else %>
	       | <%= button_to 'VHS', videos_rent_form_url(:video_id => @video.id, :category_id => @category_id = 2 ), method: :post, class: "btn btn-success btn-sm active" %>
	   <% end %>

	   <% if @video.bluray_copies == 0 %>
	       <h5><strong><span class="badge bg-secondary">Out of BLU-RAY copies!</span></strong></h5> 
	   <% else %>
	       | <%= button_to 'BLU-RAY', videos_rent_form_url(:video_id => @video.id, :category_id => @category_id = 3 ), method: :post, class: "btn btn-success btn-sm active" %>
	   <% end %>
	 </tr>
	</table>   --------        <strong>OR</strong>       --------
<% else %>
        <%= link_to 'Rent Now!', new_customer_session_path, class: "btn btn-success btn-lg active" %> <br/ >   --------        <strong>OR</strong>       --------
<% end %>

<br/>

<%= form_tag charges_path, id: 'chargeForm' do %>
    <script src="https://checkout.stripe.com/checkout.js"></script>
    <%= hidden_field_tag 'stripeToken'%>
    <%= hidden_field_tag 'video_id', @video.id %>  
    <%= hidden_field_tag 'amount', @video.rent_price*2*100 %>  
    <%= hidden_field_tag 'stripeEmail' %>
	<% if customer_signed_in? %>
	    <button id="btn-buy" type="button" class="btn btn-success btn-lg active"><span class="glyphicon glyphicon-ok"></span>Buy Now!</button> | <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Add to Cart</button>

		<script>
		   var handler = StripeCheckout.configure({
			   key: '<%= Rails.configuration.stripe[:publishable_key] %>',
			   token: function(token, arg){
			     document.getElementById("stripeToken").value = token.id;
			     document.getElementById("stripeEmail").value = token.email;
			     document.getElementById("chargeForm").submit();
			  }
		   });
		   document.getElementById('btn-buy').addEventListener('click', function(e) {
		       handler.open({
			 video_id: '<%= @video.id %>',
			 name: '<%= @video.name %>',
			 description: 'BUY NOW ($<%= @video.rent_price*2 %>)',
			 amount: document.getElementById("amount").value
		      });
		   e.preventDefault();
		   })
		</script>
	<% else %>
           <%= link_to 'Buy Now!', new_customer_session_path, class: "btn btn-success btn-lg active" %>
	<% end %>
<% end %>

<br/><br/>

<% if customer_signed_in? %>


	<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
		<h5 class="modal-title" id="exampleModalLabel">Add Item/s</h5>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		  <span aria-hidden="true">&times;</span>
		</button>
	      </div>
	      <div class="modal-body">
	       
			<%= form_for @cart_item do |f| %>
			  <%= f.hidden_field :customer_id, :value => current_customer.id unless !customer_signed_in? %>
			  <%= f.hidden_field :video_id, :value => @video.id %>
			  <% if @video.stock == 0 %>
			    <% if @waitlist.nil? %>
			       <h5><strong><span class="badge bg-secondary">Joined!</span></strong></h5> 
			    <% else %>
			       <h5><strong><span class="badge bg-secondary">Out of stock</span></strong></h5> 
			       <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#exampleModalCenter">Email me when available</button>
			    <% end %>
			  <% else %>
			     Qty: <%= f.number_field :quantity, :value => 1, :min => 1 , :max => @video.stock %><small> <%= pluralize( @video.stock , 'item') %> in stock.</small><br/><br/>
			     <%= f.submit "Add to Cart ", class: "btn btn-primary" %>
                	     <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			  <% end %>
			<% end %>

	      </div>
	    </div>
	  </div>
	</div>
    <% end %>


	<!-- Modal -->
	<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
		<h4 class="modal-title" id="exampleModalLongTitle"><strong>Join Waitlist</strong></h4>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		  <span aria-hidden="true">&times;</span>
		</button>
	      </div>

	    <%= form_for @waitlist do |f| %>
	      <div class="modal-body">
	   <% if flash[:error].present? %>
		<div id="error_explanation">
		  <p><%= flash[:error] %></p>
		</div>
           <% end %>
        <p>We will inform you when the item arrives in stock. Please leave your valid email address below.</p>
        <% if customer_signed_in? %> 
            <strong>Your Email: </strong><%= f.text_field :email, :value => @customer.email, disabled: "disabled", class: "form-control" %>
            <%= f.hidden_field :email, :value => @customer.email %>
            <%= f.hidden_field :video_id, :value => @video.id %>
        <% else %>
          <strong>Your Email: </strong><%= f.text_field :email, :placeholder => "Email", class: "form-control" %>
          <%= f.hidden_field :video_id, :value => @video.id %>
        <% end %>
      </div>
      <div class="modal-footer">
        <%= f.submit "Join", class: "btn btn-primary" %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
       <% end %>
      </div>
    </div>
  </div>
</div>


<% if user_signed_in? %>
<br/>
<h5>Avaliable copies </h5>
<div>
<table class="table table-borderless">
  <tr class="table-light">
    <td>
       <strong>DVD copies: </strong><%= @video.dvd_copies %>
    </td>
    <td>
         <strong>VHS copies: </strong><%= @video.vhs_copies %>
    </td>
    <td>
         <strong>BLU-RAY copies: </strong><%= @video.bluray_copies %>
    </td>
  </tr>
</table>
</div>
<% end %>




<br/>
<% if can? :update, @video %>
  <%= link_to 'Edit', edit_video_path, class: "btn btn-outline-warning btn-sm" %> ||
<% end%>

<% if can? :destroy, @video %>
  <%= link_to 'Delete', @video, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %>
<% end%>
<br/>
<h3>Reviews</h3>
<br/>
<br/>
<% if @video.reviews.empty? %>
  <h6><strong>Be the first to add a review.</strong></h6>
<% else %>
   <%= render @video.reviews.limit(4) %> 
   <% if @video.reviews.count > 4 %>
     <div class="col d-flex justify-content-center">
        <%= link_to "See more reviews..", '' %>
     </div>
   <% end %>

<% end %>
<br/><hr />
<div class="card border-light mb-3" style="max-width: 18rem;">
  <div class="card-header"><strong>New Review</strong></div>
  <div class="card-body">
	<div>
	<%= simple_form_for([@video, @video.reviews.build], remote: true) do |f| %>
	   <div id="rating-form">
	      <%= f.input :rating %>
	   </div>
	   <%= f.input :comment, placeholder: "Add description here.." %><br >
	   <%= f.button :button, type: :submit %>
	<% end %>
	</div>
  </div>
</div>

<br/>
<%= link_to 'Back', videos_path, class: "btn btn-outline-secondary" %>

<script>
  $('.review-rating').raty({
    size: 32,
    path: '/javascript/packs',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
   });
</script>