config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  resources :replies
  mount Notifications::Engine => "/notifications"
 resources :waitlists
 resources :line_items
 resources :carts
 resources :categories

 post 'line_items', to: 'line_items#show'
 get 'checkout', to: 'checkouts#show'

 get 'videos/index2'

 get 'purchases/orders'
 get 'purchases/previous_purchases'
 post 'purchases/show'

 get 'rentals_list/show'
 delete 'rentals_list/destroy', to: 'rentals_list#destroy'

 resources :charges
 resources :purchases, only: [:show]

 post 'videos/rent_form' 

 post 'videos/clear_cart' 
 get 'videos/cart' 

 get 'cart_list/show'

 post 'videos/add_to_cart/:id', to: 'videos#add_to_cart', as: 'add_to_cart' 
 delete 'videos/remove_from_cart/:id', to: 'videos#remove_from_cart', as: 'remove_from_cart' 

 devise_scope :user do
   get '/admin/sign_out' => 'devise/sessions#destroy'
 end


 devise_scope :customer do
   get '/home/sign_out' => 'devise/sessions#destroy'
 end

  resources :actors
  resources :videos do
   resources :reviews
   collection do
    get :autocomplete
   end
  end
  
  get 'users/edit_profile'
  devise_for :customers, path: 'home'
  devise_for :users, path: 'admin', :skip => [:registrations]

  scope '/admin' do 
    resources :genres
    resources :roles
    resources :users
  end

  scope '/home' do 
    resources :customers
  end

  scope '/customer' do
    get 'rentals_list/show'
    resources :copies
    resources :rent_items
    resources :cart_items
    resources :rentals_list, only: [:show]
  end   

  root :to => "videos#index" 

  post 'copies/new', to: 'copies#new'
  get '/users/clear', to: 'users#clear', as: 'clear'


  mount Sidekiq::Web => '/sidekiq'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-custom">
     <%= link_to 'Store', main_app.root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">

        <li class="nav-item">
            <% link_to 'About Me', main_app.root_path, class: "nav-link" %>
        </li>

        <% if cart_has_items %>
          <%= link_to cart_path(@cart), class: "navbar-item button is-warning" do %>
            <span class="icon is-small">
              <i class="fa fa-shopping-cart"></i>
            </span>
            <span>Cart
              <%= cart_count_over_one %>
            </span>
          <% end %>
         <% end %>

        <% if customer_signed_in? %>

              <span class="navbar-text">
		   Signed in as <%= current_customer.email %>.  Not you?<br/>
	      </span>

              <li class="nav-item">
                 <%= link_to "Edit Profile", edit_customer_registration_path, class: "nav-link" %>
              </li>

              <li class="nav-item">
		<div id="rental_list">
  		    <%= render 'rentals_list/rentals_list' %>
		</div>
              </li>
              <li class="nav-item">
		<div>
  		    <%= render 'cart_list/cart_list' %>
		</div>
              </li>


            <li class="nav-item">
               <%= link_to "Sign Out", destroy_customer_session_path, method: :delete, class: "nav-link" %>
              </li>
</ul>

<ul class="navbar-nav">
        <% elsif user_signed_in? %>

		    <li class="nav-item">
                        <%= link_to "Videos", main_app.videos_index2_path, class: "nav-link" %>
		    </li>

		    <li class="nav-item">
                        <%= link_to "Users", main_app.users_path, class: "nav-link" %>                
		    </li>


		    <li class="nav-item">
		         <%= link_to "Roles", main_app.roles_path, class: "nav-link" %>
		    </li>

		    <li class="nav-item">
		         <%= link_to "Categories", main_app.categories_path, class: "nav-link" %>
		    </li>

 		     <li class="nav-item">
		         <%= link_to "Orders",  main_app.purchases_orders_path, class: "nav-link" %>
		     </li>

      <% if Notification.unread_count(current_user) == 0 %>
                    <li class="nav-item">
		         <%= link_to "Notifications", notifications_path, class: "nav-link" %>
		    </li>
      <% else %>
		    <li class="nav-item">
		         <%= link_to notifications_path do %>
<span class="badge badge-primary badge-pill"><%= Notification.unread_count(current_user) %></span>
                         <% end %>
		    </li>

                     <li class="nav-item">
                       <small class="text-white bg-dark">Notifications</small>
                     </li>

       <% end %>
         <% else %> 
              <li class="nav-item">
		<%= link_to "Sign Up", new_customer_registration_path, class: "nav-link" %> 
              </li>

              <li class="nav-item">
          	<%= link_to "Sign In", new_customer_session_path, class: "nav-link" %>
              </li>
        <% end %>

      </ul>
  </div> 
  <% if @current_user && @current_user.admin? || @current_user && @current_user.super_user? %>
 <span class="navbar-text">
     Signed in as <br/>
 </span>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           <%= current_user.email %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "My Profile", main_app.users_edit_profile_path, class: "nav-link dropdown-item" %>
          <%= link_to "Sign out",  main_app.destroy_user_session_path, method: :delete, class: "nav-link dropdown-item text-danger" %>
        </div>
     </li>
.  Not you?<br/>
   <% elsif customer_signed_in? %>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           <strong> My Account </strong>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Orders", purchases_previous_purchases_path, class: "nav-link dropdown-item" %>
          <%= link_to "Cart", videos_cart_path, class: "nav-link dropdown-item" %>                
          <%= link_to "Whishlist", '#', class: "nav-link dropdown-item" %>
        </div>
     </li>
   <% end %>
</nav>