config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  resources :replies
  mount Notifications::Engine => "/notifications"
 resources :waitlists
 resources :line_items
 resources :carts
 resources :categories

 post 'line_items', to: 'line_items#show'
 get 'checkout', to: 'checkouts#show'

 get 'videos/index2'

 get 'purchases/orders'
 get 'purchases/previous_purchases'
 post 'purchases/show'

 get 'rentals_list/show'
 delete 'rentals_list/destroy', to: 'rentals_list#destroy'

 resources :charges
 resources :purchases, only: [:show]

 post 'videos/rent_form' 

 post 'videos/clear_cart' 
 get 'videos/cart' 

 get 'cart_list/show'

 post 'videos/add_to_cart/:id', to: 'videos#add_to_cart', as: 'add_to_cart' 
 delete 'videos/remove_from_cart/:id', to: 'videos#remove_from_cart', as: 'remove_from_cart' 

 devise_scope :user do
   get '/admin/sign_out' => 'devise/sessions#destroy'
 end


 devise_scope :customer do
   get '/home/sign_out' => 'devise/sessions#destroy'
 end

  resources :actors
  resources :videos do
   resources :reviews
   collection do
    get :autocomplete
   end
  end
  
  get 'users/edit_profile'
  devise_for :customers, path: 'home'
  devise_for :users, path: 'admin', :skip => [:registrations]

  scope '/admin' do 
    resources :genres
    resources :roles
    resources :users
  end

  scope '/home' do 
    resources :customers
  end

  scope '/customer' do
    get 'rentals_list/show'
    resources :copies
    resources :rent_items
    resources :cart_items
    resources :rentals_list, only: [:show]
  end   

  root :to => "videos#index" 

  post 'copies/new', to: 'copies#new'
  get '/users/clear', to: 'users#clear', as: 'clear'


  mount Sidekiq::Web => '/sidekiq'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/cart_list_controller.rb
class CartListController < ApplicationController
  def show
    @cart_items = current_customer.cart_items
    @total_amt = current_customer.cart_items.collect { |cart_item| cart_item.unit_price*cart_item.quantity }.sum

   end

end

app/views/cart_list/_cart_list.html.erb
<% link_to "#{current_rent.rent_items.size} items with a value of #{ current_rent.subtotal }$", rentals_list_show_path %>

<%= link_to "Cart", cart_list_show_path, class: "nav-link" %>

app/views/cart_list/_cart_lists_item.html.erb
<h1>Shopping Cart</h1><br><br>

<% if @cart_items.empty? %>
<h4>You don't have any items in your cart. Let's get shopping!</h4>
<br/><br/>
  <div>
   <%= link_to 'Start Shopping', root_path, class: "btn btn-primary btn-lg active"%>
  </div>
<br/><br/>
<% else %>
<% @cart_items.each do |item| %>
	
	<h4><strong><%= link_to item.video.name, item.video %></strong></h4>
      <div>
        <%= image_tag(item.video.thumbnail, size: '150x125', class: "img-responsive") %>
      </div>
<br/>
      <small><h6>Item price: $<%= item.video.rent_price*2 %></h6></small>
	<%= form_for item, remote: true do |f| %>

	        <%= f.hidden_field :customer_id, :value => current_customer.id %>
		<%= f.hidden_field :video_id, :value => item.video.id %>
		Qty:  <%= f.number_field :quantity, :value => item.quantity.to_i, :min => 1, :max => item.quantity.to_i+item.video.stock %>
		<%= f.submit "Update item", class: "btn btn-outline-info btn-sm" %>
               <div>
		<br/><%= button_to "Remove Item", cart_item_path(item), method: :delete, data: { confirm: "Are you sure? " }, remote: true, class: "delete" %>
               </div>
	<% end %>
<br />

	<h4>Subtotal: $<%= item.total %></h4><hr />
<% end %>
<br/><br/>
   <%= button_to 'Empty Cart', @cart, method: :delete, data: { confirm: "Are you sure? " }, class: "button is-danger" %>
<br/><br/>
<h4>Items(<strong><%= @cart_items.count %>)</strong></h4>
<h3>Total Amount: <strong>$<%= @total_amt %></strong></h3>
<br/>
<%= form_tag charges_path, id: 'chargeForm' do %>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
    <script src="https://checkout.stripe.com/checkout.js"></script>
    <%= hidden_field_tag 'stripeToken'%>
    <%= hidden_field_tag 'amount',  @total_amt*100 %>  
    <%= hidden_field_tag 'stripeEmail' %>
	<% if customer_signed_in? %>
	    <button id="btn-buy" type="button" class="btn btn-success btn-lg active"><span class="glyphicon glyphicon-ok"></span>CheckOut --></button>
		<script>
		   var handler = StripeCheckout.configure({
			   key: '<%= Rails.configuration.stripe[:publishable_key] %>',
			   token: function(token, arg){
			     document.getElementById("stripeToken").value = token.id;
			     document.getElementById("stripeEmail").value = token.email;
			     document.getElementById("chargeForm").submit();
			  }
		   });
		   document.getElementById('btn-buy').addEventListener('click', function(e) {
		       handler.open({
			 description: 'CHECKOUT ($<%= @total_amt %>)',
			 amount: document.getElementById("amount").value
		      });
		   e.preventDefault();
		   })
		</script>
	<% else %>
           <%= link_to 'CheckOut -->', new_customer_session_path, class: "btn btn-success btn-lg active" %>
	<% end %>
<% end %>
<br/>
<% end %>

app/views/cart_list/destroy.js.erb
$('.delete').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/cart_list/show.html.erb
<div>
  <%= render 'cart_lists_item' %>
</div>